# Generated by Django 5.1.3 on 2024-11-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodology',
            name='instructions',
            field=models.CharField(default=1, max_length=512, verbose_name='Инструкции'),
            preserve_default=False,
        ),
    ]
