# Generated by Django 5.1.3 on 2024-11-24 18:49

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_methodology_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('military_number', models.CharField(max_length=50, verbose_name='Номер военнослужащего')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kz', 'Казахский')], max_length=2, verbose_name='Язык')),
                ('file', models.FileField(upload_to=chatbot.models.report_file_path, verbose_name='Файл отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
