# Generated by Django 5.1.3 on 2024-11-25 01:57

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chatbot.models.report_file_path, verbose_name='Файл отчета'),
        ),
    ]
